### ISSUE TITLE
Missed BaseTask class and other contracts

### ISSUE THREAD

**Issue by sfortop** [oscarotero/GettextRobo#2]
> Class 'Robo\Task\BaseTask' not found

```
    "require": {
        "gettext/gettext": "v4.1.0",
        "gettext/robo": "v3.0.0"
    }
```

**Comment by oscarotero** [comment]
Are you using composer to install and load the dependencies?

**Comment by sfortop** [comment]
Sure. I'm used composer
Main error - incorrect dependency for gettext/robo
missed required section in composer.json of package

current incorrect
```
    "require": {
        "php": ">=5.4",
        "gettext/gettext": "4.*"
    },

```

e.g. correct 
```
    "require": {
        "php": ">=5.4",
        "gettext/gettext": "4.*",
	"consolidation/robo": "1.0.5"
    },
```

**Comment by oscarotero** [comment]
Ah, ok. I was not sure if robo should be included as a dependency or not (this is a task for robo, it's supposed to have robo installed, and sometimes it's installed globally), but maybe you're right. I've updated composer.json file.
